import{a as g,S as y,i as p}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&d(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const u={PIXABAY:{PATH:"https://pixabay.com/api/",KEY:"44444020-42ceddb875011e5970bd122af",PER_PAGE:15}},b=async(t,r=1)=>await g.get(u.PIXABAY.PATH,{params:{key:u.PIXABAY.KEY,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:u.PIXABAY.PER_PAGE}}),L=t=>`
    <a href="${t.largeImageURL}" class="item">
      <img src="${t.webformatURL}" alt="" alt="${t.tags}"/>
      <div class="data">
        <p><b>Likes</b> <span>${t.likes}</span></p>
        <p><b>Views</b> <span>${t.views}</span></p>
        <p><b>Comments</b> <span>${t.comments}</span></p>
        <p><b>Downloads</b> <span>${t.downloads}</span></p>
      </div>
    </a>
  `,m=document.querySelector("form.form-search"),i=document.querySelector(".gallery"),n=document.querySelector(".more-imgs-btn"),f=document.querySelector(".field-input_search"),P=new y(".gallery a",{});let c=1,l=1;function h(t,r=!0){r&&(c=1),b(t,c).then(a=>{const{hits:d,totalHits:e}=a.data;i.classList.remove("is-load");const s=[];if(e===0){n.classList.add("is-hidden"),p.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"}),l=1,m.reset();return}if(l=Math.ceil(e/u.PIXABAY.PER_PAGE),l<c){n.classList.add("is-hidden"),p.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"red"});return}if(c+=1,d.forEach(o=>{s.push(L(o))}),r)i.innerHTML=s.join("");else{i.insertAdjacentHTML("beforeend",s.join(""));const o=i.querySelector(".item");window.scrollBy({top:o.getBoundingClientRect().height*2,behavior:"smooth"})}l>1&&n.classList.remove("is-hidden"),c>l&&n.classList.add("is-hidden"),P.refresh()}).catch(a=>{console.log(a),i.classList.remove("is-load"),p.error({message:`Sorry, something went wrong! ${a.message}`,position:"topRight",color:"red"})})}m&&m.addEventListener("submit",t=>{t.preventDefault(),n.classList.add("is-hidden");const r=f.value;r?(i.innerHTML="",i.classList.add("is-load"),h(r)):p.error({message:"Please enter a search term",position:"topRight",color:"red"})});n&&n.addEventListener("click",()=>{const t=f.value;h(t,!1)});
//# sourceMappingURL=commonHelpers.js.map
